---

# file: playbooks/roles/lb/tasks/etcd.yml

# - name: Include Configuration
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ ansible_os_family }}.yml"
#   when: not conf_etcd_config_only|bool

- name: Install system dependencies for synchronize
  package: name={{ item }}
  with_flattened: "{{ conf_etcd_install_dependencies|default([]) }}"
  when: not conf_etcd_config_only|bool
  tags: [ etcd ]

- name: Download etcd
  get_url: url={{ conf_etcd_download_url }} dest={{ conf_etcd_download_dir }}/{{ conf_etcd_download_filename }} sha256sum={{ conf_etcd_checksum }}
  when: not conf_etcd_config_only|bool
  tags: [ etcd ]

- name: Unarchive etcd
  unarchive: copy=no
             src={{ conf_etcd_download_dir }}/{{ conf_etcd_download_filename }}
             dest={{ conf_etcd_download_dir }}
             creates="{{ conf_etcd_download_dir }}/{{ conf_etcd_release }}/etcd"
  when: not conf_etcd_config_only|bool
  tags: [ etcd ]

- name: Copy binaries from archive into etcd dir
  synchronize: src="{{ conf_etcd_download_dir }}/{{ conf_etcd_release }}/{{ item }}"
               dest="{{ conf_etcd_dir }}"
               archive=True
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - etcd
    - etcdctl
  when: not conf_etcd_config_only|bool
  tags: [ etcd ]

- name: Add etcd upstart service
  template: src=etc/init/etcd.conf.j2
            dest=/etc/init/etcd.conf
            mode=0644
  when: ansible_service_mgr == "upstart"
  notify:
    - handle_restart_etcd
  tags: [ etcd ]

- name: Add etcd systemd service
  template: src=etc/systemd/system/etcd.service.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644
  when: ansible_service_mgr == "systemd"
  notify:
    - handle_reload_systemd
    - handle_restart_etcd
  tags: [ etcd ]
  