---

# file: playbooks/roles/common/defaults/main.yml

#
# snmpd
#
conf_snmpd_enable: false

#
# Jailkit
#
conf_jailkit_enable: false
conf_jailkit_url: "https://olivier.sessink.nl/jailkit/jailkit-2.19.tar.bz2"

#
# Docker
#
conf_docker_enable: false
