---

# file: playbooks/vars/os/distribution/MacOSX.yml

#
# Base
#
conf_hold_packages:
    - mod-pagespeed-stable
conf_unwanted_packages:
    # - chef
conf_base_packages:
    - assh
    - zsh
    - vim
    - screen
    - tmux
    - tmate
    - mosh
    - tree
    - unzip
    - whois
    - htop
    - ccze
    - subversion
    - nmap
    - dnsutils
    - wget
    - curl
    - links
    - lynx
    - traceroute
    - make
    # - "{{ var_package_git }}"
    - convmv
conf_php_cli: "/usr/bin/php"
conf_web_cron: "/etc/cron.d/wp-cron"

#
# MySQL/Percona
#
conf_mysql_conf: "/etc/mysql/my.cnf"
conf_mysql_basedir: "/usr"
conf_mysql_datadir: "/var/lib/mysql"
conf_mysql_lc_messages_dir: "/usr/share/mysql"

#
# Etckeeper
#
conf_etckeeper_lowlevel_package_manager: "dpkg"
conf_etckeeper_highlevel_package_manager: "apt"
