---

# file: playbooks/roles/db/defaults/main.yml

#
# MySQL
#
conf_mysql_flavour_debian_family: percona-xtradb-cluster
conf_mysql_version_debian_family: 5.6
conf_mysql_expire_logs_days: 3
conf_mysql_thread_stack: 576K
conf_mysql_key_buffer: 16M

#
# galeranotify
#
conf_galera_notify_enable: false
conf_galera_notify_slack_enable: false

#
# Cassandra
#
conf_cassandra_enable: false
conf_cassandra_gpg_keyserver: pool.sks-keyservers.net
conf_cassandra_gpg_key_id: A278B781FE4B2BDA
conf_cassandra_series_version: 311x
conf_cassandra_cluster_name: "cassandra_cluster"
# conf_cassandra_listen_address: 127.0.0.1
# conf_cassandra_listen_interface: eth0
conf_cassandra_start_rpc: false
conf_cassandra_rpc_address: 0.0.0.0
conf_cassandra_broadcast_rpc_address: 127.0.0.1
conf_cassandra_rpc_port: 9160
