---

# file: playbooks/roles/local/tasks/main.yml

- name: provision ~/.ssh/assh.yml (home)
  template: src=home/{{ item }}.j2 dest=~/{{ item }} mode=0644
  with_items:
    - .ssh/assh.yml
  become: false
  tags: [ assh, assh-conf ]

- name: create ControlPath directories (Unix, users)
  file: path={{ item.value.home }}/.ssh/cm state=directory owner={{ item.key }} group={{ item.key }} mode=0755
  with_dict: '{{ conf_users }}'
  when: item.value.state == "enabled"
  tags: [ assh, assh-conf ]