---

# file: playbooks/roles/db/tasks/db-enabled.yml

###################################################################
# NOTE: since Wed, 20 Apr 2016 12:39:15 +0200 we connect to MySQL #
#       via login_host=127.0.0.1 instead of Unix socket.          #
###################################################################

#
# Requirements
#
- name: install python-mysqldb (Ubuntu/Debian)
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - python-mysqldb
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == "Debian"
  ignore_errors: yes
  tags: [ mysql, mysql-users ]

#
# create DB
#
- name: create DB if enabled (defined encoding)
  mysql_db: login_host=127.0.0.1 name={{ item.value.db_name }} encoding={{ item.value.db_encoding }} state=present
  when: item.value.state == "enabled" and item.value.db_name is defined and item.value.db_encoding is defined
  with_dict: '{{ conf_vhosts_common }}'
  ignore_errors: yes
  tags: [ mysql, mysql-users ]

- name: create DB if enabled (default encoding)
  mysql_db: login_host=127.0.0.1 name={{ item.value.db_name }} state=present
  when: item.value.state == "enabled" and item.value.db_name is defined and item.value.db_encoding is not defined
  with_dict: '{{ conf_vhosts_common }}'
  ignore_errors: yes
  tags: [ mysql, mysql-users ]

#
# create DB user
#
- name: create DB user if enabled (login_host=127.0.0.1)
  mysql_user: login_host=127.0.0.1 name={{ item.value.db_user }} password={{ item.value.db_password }} host={{ item.value.db_host }} priv="{{ item.value.db_name }}.*:ALL" append_privs=no state=present
  when: item.value.state == "enabled" and item.value.db_user is defined
  with_dict: '{{ conf_vhosts_common }}'
  ignore_errors: yes
  tags: [ mysql, mysql-users ]

#
# create global DB admin user (if defined)
#
- name: create global DB user if enabled (login_host=127.0.0.1)
  mysql_user: login_host=127.0.0.1 name={{ conf_mysql_global_admin_user }} password={{ conf_mysql_global_admin_passsword }} host={{ item.value.db_host }} priv="{{ item.value.db_name }}.*:ALL" append_privs=yes state=present
  when: item.value.state == "enabled" and item.value.db_user is defined and conf_mysql_global_admin_user is defined and conf_mysql_global_admin_passsword is defined
  with_dict: '{{ conf_vhosts_common }}'
  ignore_errors: yes
  tags: [ mysql, mysql-users ]
