---

# file: playbooks/roles/db/tasks/mysql.yml

#
# Reproduce:
#
# apt purge mysql-client-core-5.7 mysql-common mysql-server-core-5.7 mysql-server-core-5.7 ; rm -r /var/lib/mysql-files/* /var/lib/mysql/* /etc/mysql/debian.cnf /etc/mysql/ /root/.my.cnf
#
# /etc/mysql/
# ├── conf.d
# │   ├── mysql.cnf
# │   └── mysqldump.cnf
# ├── debian.cnf
# ├── debian-start
# ├── my.cnf
# ├── my.cnf.fallback
# ├── mysql.cnf
# └── mysql.conf.d
#     ├── mysqld.cnf
#     └── mysqld_safe_syslog.cnf
#

- name: install MySQL (Debian family)
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - "{{ conf_mysql_flavour_debian_family }}-server-{{ conf_mysql_version_debian_family }}"
    - "{{ conf_mysql_flavour_debian_family }}-client-{{ conf_mysql_version_debian_family }}"
    - python-mysqldb
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == "Debian"
  tags: [ mysql ]
