---

# file: playbooks/roles/db/tasks/percona.yml

- name: deploy /usr/local/bin/galeranotify.py
  template: src=usr/local/bin/galeranotify.py.j2 dest=/usr/local/bin/galeranotify owner=root group={{ conf_root_group }} mode=0755
  tags: [ mysql, percona ]

- name: apparmor disable mysqld
  file: src=/etc/apparmor.d/usr.sbin.mysqld dest=/etc/apparmor.d/disable/usr.sbin.mysqld state=link force=yes
  notify: handle_reload_apparmor_mysql
  ignore_errors: yes
  tags: [ mysql, percona ]

- name: check to determine if galera is aready installed
  # shell: dpkg-query -s percona-xtradb-cluster-galera-3.x &>/dev/null && echo "installed" || echo "bootstrap"
  # shell: dpkg-query -l | grep percona-xtradb-cluster-galera-3.x &>/dev/null && echo "installed" || echo "bootstrap"
  shell: "dpkg-query -s percona-xtradb-cluster-galera-3.x"
  ignore_errors: yes
  register: bootstrap_check
  always_run: yes
  tags: [ mysql, percona ]

- debug: var=bootstrap_check.rc
  tags: [ mysql, percona ]

- name: percona apt-key (Debian family)
  # apt_key: url=http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona state=present
  apt_key: data="{{ lookup('file', 'percona/percona.gpg') }}" state=present
  when: ansible_os_family == "Debian"
  tags: [ mysql, percona ]

- name: percona repo (Debian family)
  apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' update_cache=yes
  when: ansible_os_family == "Debian"
  tags: [ mysql, percona ]

- name: remove conflicting MySQL packages (Debian family)
  apt: pkg={{ item }} state=absent
  with_items:
    - mysql-server-core-5.5
    - mysql-client-core-5.5
    - mysql-client-5.5
    - mysql-server-5.6
    - mysql-common-5.6
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == "Debian"
  tags: [ mysql, percona ]

- name: Prepare for bootstrap (gcomm)
  lineinfile: "dest=/etc/mysql/my.cnf regexp='^wsrep_cluster_address' line='wsrep_cluster_address = gcomm://' state=present"
  when: bootstrap_check.rc == 1 and conf_wsrep_master is defined and conf_wsrep_master == true
  tags: [ mysql, percona]

- name: Prepare for bootstrap (sst)
  lineinfile: "dest=/etc/mysql/my.cnf regexp='^wsrep_sst_auth' line='wsrep_sst_auth = deploy' state=present"
  when: bootstrap_check.rc == 1 and conf_wsrep_master is defined and conf_wsrep_master == false
  tags: [ mysql, percona]

- name: Prepare for bootstrap (sst)
  lineinfile: "dest=/etc/mysql/my.cnf regexp='^wsrep_sst_method' line='wsrep_sst_method = rsync' state=present"
  when: bootstrap_check.rc == 1 and conf_wsrep_master is defined and conf_wsrep_master == false
  tags: [ mysql, percona]

- name: Prepare for bootstrap (mysql dir)
  file: path=/var/lib/mysql state=directory mode=0750
  when: bootstrap_check.rc == 1 and conf_wsrep_master is defined and conf_wsrep_master == true
  tags: [ mysql, percona]

- name: install Percona XtraDB Cluster (Debian family)
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - percona-xtradb-cluster-server-5.6
    - percona-xtradb-cluster-client-5.6
    - percona-xtradb-cluster-galera-3.x
    - python-mysqldb
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == "Debian"
  ignore_errors: yes
  tags: [ mysql, percona ]

- name: install xinetd (Debian family)
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - xinetd
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == "Debian" and conf_env != "development" and conf_galera_cluster == true
  ignore_errors: yes
  tags: [ mysql, percona, clustercheck ]

- name: update /etc/services (Debian family)
  lineinfile: "dest=/etc/services line='mysqlchk        9200/tcp                        # mysqlchk' insertafter='^xinetd' state=present"
  when: ansible_os_family == "Debian" and conf_env != "development" and conf_galera_cluster == true
  tags: [ mysql, percona, clustercheck ]

- name: update /etc/xinetd.d/mysqlchk (Debian family)
  lineinfile: "dest=/etc/xinetd.d/mysqlchk line='        server_args = {{ conf_mysql_clustercheck_user }} {{ conf_mysql_clustercheck_password }} {{ conf_mysql_clustercheck_available_when_donor }} /dev/null 0' insertafter='^        # 55-to-56 upgrade' state=present"
  notify: handle_restart_xinetd
  when: ansible_os_family == "Debian" and conf_env != "development" and conf_galera_cluster == true
  tags: [ mysql, percona, clustercheck ]

- name: create DB clustercheck user
  mysql_user: check_implicit_admin=yes name={{ conf_mysql_clustercheck_user }} password={{ conf_mysql_clustercheck_password }} host=% priv="*.*:PROCESS" state=present
  when: conf_env != "development" and conf_galera_cluster == true
  ignore_errors: yes
  tags: [ mysql, percona, clustercheck ]
