---

# playbooks/roles/db/handlers/main.yml

- name: handle_reload_apparmor_mysql
  shell: apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

- name: handle_mysql_import
  mysql_db: name=mysql state=import target=/root/latest.sql.bz2
  notify: handle_restart_mysql

- name: handle_restart_mysql
  service: name=mysql state=restarted

- name: handle_reload_mysql
  service: name=mysql state=reloaded

- name: handle_restart_xinetd
  service: name=xinetd state=restarted
