---

# file: playbooks/roles/web/tasks/geoip.yml

- name: create /usr/local/share/GeoIP directory
  file: path=/usr/local/share/GeoIP state=directory owner=root group={{ conf_root_group }} mode=0755
  tags: [ geoip ]

#- name: unarchive geoip
#  unarchive: src={{ conf_geoip_url }} dest=/usr/local/share/GeoIP copy=no owner=root group={{ conf_root_group }} mode=0644
#  tags: [ geoip ]

- name: Upgrade GeoLiteCity.dat.gz
  action: shell {{ item }} chdir=/tmp
  with_items:
    - rm -f GeoLiteCity.dat
    - wget -cO GeoLiteCity.dat.gz "{{ conf_geoip_url }}"
    - gunzip GeoLiteCity.dat.gz
    - mv GeoLiteCity.dat /usr/local/share/GeoIP/GeoLiteCity.dat
  tags: [ geoip ]
