---

# file: playbooks/roles/web/tasks/jenkins.yml

################
# JENKINS BASE #
################
- name: jenkins apt-key (Ubuntu)
  apt_key: data="{{ lookup('file', 'jenkins/jenkins.gpg') }}" state=present
  when: ansible_os_family == "Debian"
  tags: [ jenkins, ssl ]

- name: disable repo ppa:vbernat/jenkins-1.5 (Ubuntu)
  apt_repository: repo='deb http://ppa.launchpad.net/vbernat/jenkins-1.5/ubuntu {{ ansible_distribution_release }} main' update_cache=yes state=absent
  when: ansible_os_family == "Debian"
  tags: [ jenkins, ssl ]

- name: enable repo ppa:vbernat/jenkins-1.6 (Ubuntu)
  apt_repository: repo='deb http://ppa.launchpad.net/vbernat/jenkins-1.6/ubuntu {{ ansible_distribution_release }} main' update_cache=yes
  when: ansible_os_family == "Debian"
  tags: [ jenkins, ssl ]

- name: be sure latest jenkins packages are installed (Ubuntu)
  apt: pkg={{ item }} state=latest
  with_items:
    - jenkins
  when: ansible_os_family == "Debian"
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: [ jenkins, ssl ]

- name: enable jenkins
  lineinfile: "dest=/etc/default/jenkins regexp='^ENABLED=0' line='ENABLED=1'"
  tags: [ jenkins, ssl ]
