---

# file: playbooks/roles/web/tasks/jenkins.yml

################
# JENKINS BASE #
################
- name: jenkins apt-key (Debian family)
  apt_key: data="{{ lookup('file', 'jenkins/jenkins.gpg') }}" state=present
  when: ansible_os_family == "Debian"
  tags: [ jenkins, ssl ]

# - name: disable repo ppa:vbernat/jenkins-1.5 (Debian family)
#   apt_repository: repo='deb http://ppa.launchpad.net/vbernat/jenkins-1.5/ubuntu {{ ansible_distribution_release }} main' update_cache=yes state=absent
#   when: ansible_os_family == "Debian"
#   tags: [ jenkins, ssl ]

- name: deploy jenkins conf (Debian family)
  template: src=etc/{{ item }}.j2 dest=/etc/{{ item }} owner=root group={{ conf_root_group }} mode=0644
  with_items:
    - default/jenkins
  # notify: handle_reload_varnish
  when: ansible_os_family == "Debian"
  tags: [ jenkins, ssl ]

- name: enable deb http://pkg.jenkins.io/debian-stable binary/ (Debian family)
  apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' update_cache=yes
  when: ansible_os_family == "Debian"
  tags: [ jenkins, ssl ]

- name: be sure latest jenkins packages are installed (Debian family)
  apt: pkg={{ item }} state=latest
  with_items:
    - jenkins
  when: ansible_os_family == "Debian"
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: [ jenkins, ssl ]

- name: enable jenkins
  lineinfile: "dest=/etc/default/jenkins regexp='^ENABLED=0' line='ENABLED=1'"
  tags: [ jenkins, ssl ]
