---

# file: playbooks/roles/web/tasks/main.yml

- import_tasks: php.yml

#
# GlusterFS
#
- import_tasks: glusterfs.yml
  when: conf_glusterfs_enable == true
  ignore_errors: yes

#
# Memcached
#
- import_tasks: memcached.yml
  when: conf_memcached_enable is defined and conf_memcached_enable == true

#
# MogileFS
#
- import_tasks: mogilefs.yml
  when: conf_mogilefs_enable is defined and conf_mogilefs_enable == true

#
# ruby
#
- import_tasks: ruby.yml
  when: ansible_distribution == "Ubuntu"

#
# rbenv
#
- import_tasks: rbenv.yml

#
# nodejs
#
- import_tasks: nodejs.yml

#
# varnish
#
- import_tasks: varnish.yml
  when: conf_varnish_enable is defined and conf_varnish_enable == true

#
# apache2
#
- import_tasks: apache2.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

#
# nginx
#
- import_tasks: nginx.yml
  when:
    - conf_nginx_enable is defined and conf_nginx_enable == true  
    - ansible_os_family == "Debian" or ansible_os_family == "RedHat"

#
# HHVM
#
- import_tasks: hhvm.yml
  when:
    - conf_hhvm_enable is defined and conf_hhvm_enable == true  
    - ansible_os_family == "Debian"

#
# mod_pagespeed
#
# - import_tasks: mod-pagespeed.yml
#   when: ansible_os_family == "Debian" and conf_mod_pagespeed == true

#
# composer
#
- import_tasks: composer.yml

- name: wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest={{ conf_bin_path }}/wp owner=root {{ conf_root_group }} mode=0755 force=yes
  ignore_errors: yes
  tags: [ wp-cli, apache2 ]

# - name: memcached service state
#   service: name=memcached state=started enabled=yes
#   when: ansible_os_family == "Debian"
#   tags: [ apache2, apache2-conf ]

# - debug: msg="System {{ inventory_hostname }} has conf_vhosts_file {{ conf_vhosts_file }} env is {{ conf_env }}"
# - debug: msg="System {{ inventory_hostname }} has conf_vhosts {{ conf_vhosts }}"
#
# - debug: msg="System {{ inventory_hostname }} deploying vhost {{ item.key }}"
#  when: item.value.enabled == True
#  with_dict: '{{ conf_vhosts_common }}'

#
# Debug
#
# - name: debug '{{ conf_vhosts_common }}'
#   debug: var='{{ conf_vhosts_common }}'
#   with_dict: '{{ conf_vhosts_common }}'
#   tags: vhosts

#
# htpasswd
#
- import_tasks: htpasswd.yml

#
# vhosts archived
#
- import_tasks: vhosts-archived.yml

#
# vhosts enabled
#
- import_tasks: vhosts-enabled.yml

#
# vhosts not enabled (disabled, archived or purged)
#
- import_tasks: vhosts-not_enabled.yml

#
# bedrock
#
- import_tasks: bedrock.yml

#
# bedrock
#
- import_tasks: typo3.yml

#
# Jenkins
#
- import_tasks: jenkins.yml
  when: conf_jenkins_enable is defined and conf_jenkins_enable == true

#
# GeoIP
#
- import_tasks: geoip.yml
  when: conf_geoip_enable is defined and conf_geoip_enable == true

#
# Thumbor
#
- import_tasks: thumbor.yml
  when: conf_thumbor_enable is defined and conf_thumbor_enable == true

#
# Serf
#
- import_tasks: serf.yml
  when: conf_serf_enable is defined and conf_serf_enable == true

#
# WoodWing
#
- import_tasks: woodwing.yml
  when: conf_woodwing_enable is defined and conf_woodwing_enable == true
