---

# file: playbooks/roles/web/tasks/ruby.yml

- name: ruby PPA (Ubuntu)
  apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=yes
  when: ansible_distribution == "Ubuntu"
  ignore_errors: yes
  tags: [ ruby, update ]

- name: be sure ruby{{ conf_ruby_version_debian_family }} packages packages are installed (Ubuntu)
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - libruby{{ conf_ruby_version_debian_family }}
    - ruby{{ conf_ruby_version_debian_family }}
  when: ansible_distribution == "Ubuntu"
  ignore_errors: yes
  tags: [ ruby ]