---

# file: playbooks/roles/web/tasks/thumbor.yml

- name: Thumbor group
  action: group name={{ item }} state=present
  with_items:
    - "{{ conf_thumbor_group }}"
  tags: [ thumbor ]

- name: Thumbor system user
  user: name={{ item }} group={{ conf_thumbor_group }} comment="Thumbor System User" system=yes generate_ssh_key=yes  state=present
  with_items:
    - "{{ conf_thumbor_user }}"
  tags: [ thumbor ]

- name: Thumbor dependencies (Debian family)
  apt: pkg={{ item }} state=latest
  with_items:
    - ffmpeg
    - gifsicle
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libgtk2.0-dev
    - libjpeg-turbo-progs
    - python-numpy
    - python-pycurl
    - python-virtualenv
    - webp
    - python-opencv
    - libcurl4-gnutls-dev
    - libgnutls28-dev
  when: ansible_os_family == "Debian" 
  tags: [ thumbor ]

- name: create Thumbor tmp folder
  file: path={{ item }} owner={{ conf_thumbor_user }} group={{ conf_thumbor_group }} mode=0755 state=directory
  with_items:
    - "{{ conf_thumbor_tmp_path }}"
    - "{{ conf_thumbor_log_path }}"
  tags: [ thumbor ]

# - name: Checkout imgdb2 repo to /opt/imgdb2
#   git:
#     repo: "{{ conf_thumbor_imgdb2_repo }}"
#     version: master
#     dest: /opt/imgdb2
#     force: yes
#     update: yes
#     accept_hostkey: yes
#   tags: [ thumbor ]

- name: Set owner and group to thumbor on /opt/imgdb2
  file:
    path: /opt/imgdb2
    owner: thumbor
    group: thumbor
    recurse: yes
  tags: [ thumbor ]

- name: Create Python virtualenv
  pip:
    requirements: /opt/imgdb2/requirements.txt
    virtualenv: /opt/imgdb2/venv
    virtualenv_python: python2
  tags: [ thumbor ]

- name: Set symlink in venv for thumbor custom loader (mogile)
  file:
    src: /opt/imgdb2/src/thumbor_custom
    dest: /opt/imgdb2/venv/lib/python2.7/site-packages/thumbor/thumbor_custom
    owner: thumbor
    group: thumbor
    state: link
  tags: [ thumbor ]

- name: start img-proxy-serv via supervisor
  supervisorctl: name='img-proxy-serv:' state=started
  ignore_errors: yes
  tags: [ thumbor ]

- name: start mogimporter via supervisor
  supervisorctl: name=mogimporter state=started
  ignore_errors: yes
  tags: [ thumbor ]

- name: start thumbor via supervisor
  supervisorctl: name='thumbor:' state=started
  ignore_errors: yes
  tags: [ thumbor ]
