---

# file: playbooks/roles/web/tasks/varnish.yml

#### conf_varnish_version = 3
#### conf_varnish_version = 41
#### conf_varnish_version = 51

- name: Varnish Depencencies (Debian family)
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - debian-archive-keyring
    - gnupg
    - apt-transport-https
  tags: [ varnish, varnish-conf, apache2 ]

- name: Varnish apt-key (Debian family)
  apt_key:
    url: https://packagecloud.io/varnishcache/varnish{{ conf_varnish_version }}/gpgkey
    state: present
  when: ansible_os_family == "Debian" and conf_varnish_version != 3
  tags: [ varnish, varnish-conf, apache2 ]

- name: Varnish repo (Debian family)
  apt_repository: repo='deb https://packagecloud.io/varnishcache/varnish{{ conf_varnish_version }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and conf_varnish_version != 3
  ignore_errors: yes
  tags: [ varnish, varnish-conf, apache2 ]

- name: Varnish repo src (Debian family)
  apt_repository: repo='deb-src https://packagecloud.io/varnishcache/varnish{{ conf_varnish_version }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and conf_varnish_version != 3
  ignore_errors: yes
  tags: [ varnish, varnish-conf, apache2 ]

- name: be sure Varnish package is installed (Debian family)
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - varnish
  when: ansible_os_family == "Debian"
  ignore_errors: yes
  tags: [ varnish, varnish-conf, apache2 ]

- name: deploy varnish default conf (Debian family)
  template: src=etc/{{ item }}.j2 dest=/etc/{{ item }} owner=root group={{ conf_www_group }} mode=0644
  with_items:
    - default/varnish
  notify: handle_reload_varnish
  when: ansible_os_family == "Debian"
  tags: [ varnish, varnish-conf, apache2 ]

- name: deploy varnish conf
  template: src=etc/{{ item }}-{{ conf_varnish_version }}.j2 dest=/etc/{{ item }} owner=root group={{ conf_www_group }} mode=0644
  with_items:
    - varnish/default.vcl
  notify: handle_reload_varnish
  tags: [ varnish, varnish-conf, apache2 ]

- name: perms /etc/varnish/secret (Debian family)
  file: path=/etc/varnish/secret owner=root group=nagios mode=0640
  when:
      - ansible_os_family == "Debian"
      - conf_icinga_master == true or conf_icinga_satellite == true or conf_icinga_client == true
  tags: [ varnish, varnish-conf, apache2 ]

- name: varnish service state
  service: name=varnish state=started enabled=yes
  tags: [ varnish, apache2 ]