---

# file: playbooks/roles/web/tasks/varnish.yml

- name: be sure varnish package is installed (Debian family)
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - varnish
  when: ansible_os_family == "Debian"
  ignore_errors: yes
  tags: [ varnish, varnish-conf, apache2 ]

- name: varnish service state (Debian family)
  service: name=varnish state=started enabled=yes
  when: ansible_os_family == "Debian"
  tags: [ varnish, apache2 ]

- name: deploy varnish conf (Debian family)
  template: src=etc/{{ item }}.j2 dest=/etc/{{ item }} owner=root group={{ conf_www_group }} mode=0644
  with_items:
    - default/varnish
    - varnish/default.vcl
  notify: handle_reload_varnish
  when: ansible_os_family == "Debian"
  tags: [ varnish, varnish-conf, apache2 ]

- name: perms /etc/varnish/secret (Debian family)
  file: path=/etc/varnish/secret owner=root group=nagios mode=0640
  when:
      - ansible_os_family == "Debian"
      - conf_icinga_master == true or conf_icinga_satellite == true or conf_icinga_client == true
  tags: [ varnish, varnish-conf, apache2 ]
