---

# file: playbooks/roles/web/tasks/woodwing.yml

- name: check if ioncube_loader_so is installed
  stat: "path={{ conf_php_extension_dir }}/{{ conf_php_ioncube_loader_so }}"
  register: ioncube_loader_so
  when: conf_woodwing_enable is defined and conf_woodwing_enable == true
  tags: [ woodwing, ioncube_loader, php ]

- debug: var=ioncube_loader_so
  when: conf_woodwing_enable is defined and conf_woodwing_enable == true
  tags: [ woodwing, ioncube_loader, php ]

- name: create /tmp/ioncube-loader
  file: path=/tmp/ioncube-loader state=directory mode=0750
  when: not ioncube_loader_so.stat.exists
  tags: [ woodwing, ioncube_loader, php ]

- name: unarchive ioncube_loader_so
  unarchive:
    src: "{{ conf_woodwing_ioncube_url }}"
    dest: /tmp/ioncube-loader
    remote_src: true
  when: not ioncube_loader_so.stat.exists
  tags: [ woodwing, ioncube_loader, php ]

- name: remove /tmp/ioncube-loader
  file: path=/tmp/ioncube-loader state=absent mode=0750
  when: not ioncube_loader_so.stat.exists
  tags: [ woodwing, ioncube_loader, php ]
