---

# file: playbooks/roles/common/tasks/apticron.yml

- name: be sure latest apt-listchanges and apticron packages are installed (Debian family)
  apt: pkg={{ item }} state=latest
  with_items:
    - apt-listchanges
    - apticron
  when: ansible_os_family == "Debian"
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: [ apticron, apt-listchanges ]

- name: deploy /etc/apt/listchanges.conf (Debian family)
  template: src=etc/apt/listchanges.conf.j2 dest=/etc/apt/listchanges.conf owner=root group={{ conf_root_group }} mode=0644
  when: ansible_os_family == "Debian"
  tags: [ apticron, apt-listchanges ]

- name: deploy /etc/apticron/apticron.conf (Debian family)
  template: src=etc/apticron/apticron.conf.j2 dest=/etc/apticron/apticron.conf owner=root group={{ conf_root_group }} mode=0644
  when: ansible_os_family == "Debian"
  tags: [ apticron, apt-listchanges ]
