---

# file: playbooks/roles/common/tasks/base_packages.yml

- name: apt-mark hold (Debian family)
  shell: "apt-mark hold {{ item }}"
  with_items: '{{ conf_hold_packages }}'
  when: ansible_os_family == "Debian"
  ignore_errors: yes

- name: purge unwanted packages (Debian family)
  apt: pkg={{ item }} state=absent purge=yes
  with_items: '{{ conf_unwanted_packages }}'
  when: ansible_os_family == "Debian"

- name: install golang ppa (Debian Family)
  apt_repository: repo='ppa:ubuntu-lxc/lxd-stable' update_cache=yes validate_certs=False
  when: ansible_distribution == "Ubuntu"

- name: base packages (Debian family)
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items: '{{ conf_base_packages }}'
  when: ansible_os_family == "Debian"

- name: python3-pip (Ubuntu >= 14 or Debian >= 7)
  apt: pkg={{ item }} state=installed
  with_items:
    - python3-pip
  when: (ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int >= 14) or
        (ansible_distribution == "Debian" and ansible_lsb.major_release|int >= 7)

- name: base packages (RedHat/SHMZ family)
  package: name={{ item }} state=latest
  with_items: '{{ conf_base_packages }}'
  when: ansible_os_family == "RedHat" or ansible_os_family == "SHMZ"

- name: base packages (FreeBSD)
  pkgng: name={{ item }} state=latest cached=yes
  with_items: '{{ conf_base_packages }}'
  when: ansible_distribution == "FreeBSD"
  tags: [ common, pkg, base_packages ]

- name: symlink ccze
  file: src=/usr/local/bin/colorize dest=/usr/local/bin/ccze state=link
  when: ansible_distribution == "FreeBSD"
  tags: [ common, pkg, base_packages ]

- name: base packages (Darwin)
  package: name={{ item }} state=latest
  with_items:
      - '{{ conf_base_packages }}'
      - assh
  become: false
  when: ansible_os_family == "Darwin"
