---

# file: playbooks/roles/common/tasks/fail2ban.yml

- name: fail2ban packages
  package: name={{ item }} state=latest
  with_items:
    - fail2ban
  # when:
    # - ansible_os_family == "Debian"
  tags: [ fail2ban ]

- name: provision configs (Debian family)
  template: src=etc/{{ item }}.j2 dest={{ conf_local_etc_path }}/{{ item }} owner=root group={{ conf_root_group }} mode=0644
  with_items:
      - fail2ban/fail2ban.conf
  when:
    - ansible_os_family == "Debian"
  notify: handle_restart_fail2ban
  tags: [ fail2ban, fail2ban-conf ]

- name: enable fail2ban service
  service: name=fail2ban state=started enabled=yes
  tags: [ fail2ban, fail2ban-conf ]
