---

# file: playbooks/roles/common/tasks/locales.yml

- name: install
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ conf_locales_dependencies }}"
  tags: [ locales ]

- name: install (specified) language packs
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ conf_locales_language_packs_present }}"
  when: ansible_distribution == 'Ubuntu'
  notify: handle_update_locales
  tags: [ locales ]

- name: remove (specified) language packs
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ conf_locales_language_packs_absent }}"
  when: ansible_distribution == 'Ubuntu'
  notify: handle_update_locales
  tags: [ locales ]

- name: detect locale gen file
  stat:
    path: "{{ conf_locales_gen_file }}"
  register: _conf_locales_gen_file_stats
  tags: [ locales ]

- name: create locale gen file
  file:
    path: "{{ conf_locales_gen_file }}"
    state: touch
  when: _conf_locales_gen_file_stats.stat.exists == false
  tags: [ locales ]

- name: make sure (specified) locales are present
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ conf_locales_present }}"
  tags: [ locales ]

- name: make sure (specified) locales are absent
  locale_gen:
    name: "{{ item }}"
    state: absent
  with_items: "{{ conf_locales_absent }}"
  tags: [ locales ]

- name: set default locale
  template:
    src: etc/default/locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
  tags: [ locales ]
