---

# file: playbooks/roles/common/tasks/main.yml

# - include: net.yml
#   tags: [ common ]

- name: set root shell
  user: name=root shell={{ conf_root_shell }}
  tags: [ common, users, shell ]

- include: fail2ban.yml
  when: conf_fail2ban_enable is defined and conf_fail2ban_enable == true
  tags: [ common, fail2ban ]

- include: ssh.yml
  tags: [ common, ssh, sshd  ]

- include: sudo.yml
  tags: [ common, users, sudo ]

- include: cloud.yml
  when: conf_cloud_env is defined and conf_cloud_enable == true
  tags: [ common ]

# - name: define proxy settings
#   lineinfile: "dest=/etc/environment state=present line=http_proxy={{ conf_http_proxy }}"
#   when: set_http_proxy == true
#   tags: proxy

- name: deploy /etc/environment
  template: src=etc/environment.j2 dest=/etc/environment owner=root group={{ conf_root_group }} mode=0644
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu"
    - conf_http_proxy is defined
  tags: [ base_packages, yum_proxy, environment ]

- include: centos-epel.yml
  when: ansible_os_family == "RedHat" 
  tags: [ common, apt, base_packages ]

- name: template /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts owner=root group={{ conf_root_group }} mode=0644 backup=no
  when: conf_hosts_fqdn is defined
  tags: [ common, hosts ]

- include: firewall.yml
  when: conf_firewall_enable is defined and conf_firewall_enable == true
  tags: [ common, firewall ]

- include: etckeeper.yml
  when: conf_etckeeper_webhook_url is defined
  tags: [ common ]

- include: timezone.yml
  tags: [ common ]

- include: rsyslog.yml
  when: conf_rsyslog_enable is defined and conf_rsyslog_enable == true
  tags: [ common, rsyslog ]

- include: lvm.yml
  tags: [ common ]

- include: jailkit.yml
  when: and conf_jailkit_enable is defined and conf_jailkit_enable == true
  tags: [ common, jailkit, jails ]

- include: users.yml
  tags: [ common ]

- name: remove deb-src (Debian family)
  lineinfile: dest=/{{ conf_etc_path }}/apt/sources.list state=absent regexp='^deb-src'
  when: ansible_os_family == "Debian"
  tags: [ common ]

- include: base_packages.yml
  tags: [ common, apt, base_packages ]

- include: docker.yml
  when: conf_docker_enable is defined and conf_docker_enable == true
  tags: [ common, docker ]

- include: ansible.yml

- include: assh.yml
  # tags: [ common, assh, assh-conf, base_packages ]

- include: autossh.yml

- include: nullmailer.yml
  when: conf_nullmailer_enable == true
  tags: [ common, nullmailer ]

- include: snmpd.yml
  when: and conf_snmpd_enable is defined and conf_snmpd_enable == true
  tags: [ common, snmpd ]

- include: nfs.yml
  # when: conf_nfs_enable is defined and conf_nfs_enable == true
  tags: [ common, nfs ]

# Bash prompt
# - copy: src=../files/profile/nicer-bash-prompt.sh dest=/{{ conf_etc_path }}/profile.d/Z999-nicer-bash-prompt.sh owner=root group={{ conf_root_group }} mode=644
#   when: ansible_os_family == "Debian"
#  tags: [ common, prompt ]

- include: motd.yml
  tags: [ common, motd ]

- include: apticron.yml
  when: ansible_os_family == "Debian"
  tags: [ common ]

# - include: vpn.yml
#   when: conf_vpn_netname is defined
#   tags: [ common ]

- include: letsencrypt.yml
  # when:
  #   - conf_letsencrypt_enable is defined and conf_letsencrypt_enable == true
  #   - conf_letsencrypt_master is defined and conf_letsencrypt_master == true
  #   - conf_letsencrypt_cron_master is defined and conf_letsencrypt_cron_master == true
  tags: [ common, letsencrypt ]

- include: icinga.yml
  when: conf_icinga_master is defined or conf_icinga_satellite is defined or conf_icinga_client is defined
  tags: [ common ]

- include: munin.yml
  when: conf_munin_master is defined or conf_munin_client is defined
  tags: [ common ]

- include: borg.yml
  when: conf_backup_client == true
  tags: [ common ]
