---

# file: playbooks/roles/common/tasks/main.yml

# - include: net.yml
#   tags: [ common ]

- name: set root shell
  user: name=root shell={{ conf_root_shell }}
  when: conf_env != "local"
  tags: [ common, users, shell ]

- include: sudo.yml
  tags: [ common, users, sudo ]

- include: cloud.yml
  when: conf_cloud_env is defined and conf_cloud_enable == true
  tags: [ common ]

- include: centos-epel.yml
  when: ansible_os_family == "RedHat"
  tags: [ common, apt, base_packages ]

- name: template /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts owner=root group={{ conf_root_group }} mode=0644 backup=no
  when: conf_hosts_fqdn is defined
  tags: [ common, hosts ]

- include: etckeeper.yml
  when: conf_etckeeper_webhook_url is defined
  tags: [ common ]

- include: timezone.yml
  tags: [ common ]

- include: rsyslog.yml
  when: conf_rsyslog_enable is defined and conf_rsyslog_enable == true
  tags: [ common, rsyslog ]

- include: lvm.yml
  tags: [ common ]

- include: users.yml
  tags: [ common ]

- name: remove deb-src (Debian family)
  lineinfile: dest=/{{ conf_etc_path }}/apt/sources.list state=absent regexp='^deb-src'
  when: ansible_os_family == "Debian"
  tags: [ common ]

- include: base_packages.yml
  tags: [ common, apt, base_packages ]

- include: nullmailer.yml
  when: conf_nullmailer_enable == true
  tags: [ common ]

# Bash prompt
# - copy: src=../files/profile/nicer-bash-prompt.sh dest=/{{ conf_etc_path }}/profile.d/Z999-nicer-bash-prompt.sh owner=root group={{ conf_root_group }} mode=644
#   when: ansible_os_family == "Debian"
#  tags: [ common, prompt ]

- include: motd.yml
  tags: [ common, motd ]

- include: apticron.yml
  when: ansible_os_family == "Debian"
  tags: [ common ]

# - include: vpn.yml
#   when: conf_vpn_netname is defined
#   tags: [ common ]

# - include: icinga.yml
#   when: conf_icinga_master is defined or conf_icinga_satellite is defined or conf_icinga_client is defined
#   tags: [ common ]

- include: borg.yml
  when: conf_backup_client == true
  tags: [ common ]
