---

# file: playbooks/roles/common/tasks/motd.yml

- name: create /etc/update-motd.d (Debian family)
  file: path=/{{ conf_etc_path }}/update-motd.d state=directory owner=root group={{ conf_root_group }} mode=0755
  when: ansible_os_family == "Debian"
  tags: [ motd ]

- name: config motd (Debian family)
  template: src=etc/{{ item }}.j2 dest={{ conf_local_etc_path }}/{{ item }} owner=root group={{ conf_root_group }} mode=0755
  with_items:
    - update-motd.d/98-motd
  when: ansible_os_family == "Debian"
  tags: [ motd ]

# - name: config MOTD (FreeBSD)
#   template: src=bsd/motd.j2 dest=/etc/motd owner=root group=wheel mode=0644
#   when: ansible_distribution == "FreeBSD"
#   tags: [ motd ]
