---

# file: playbooks/roles/common/tasks/nullmailer.yml

- name: nullmailer PPA (12.04 only)
  apt_repository: repo='ppa:mikko-red-innovation/ppa' update_cache=yes
  when: ansible_distribution_version == "12.04" and ansible_distribution == "Ubuntu"
  tags: [ smtpd, nullmailer ]

- name: Check if nullmailer repo is already configured (RedHat Family)
  stat: path={{ nullmailer_repofile_path }}
  register: nullmailer_repofile_result
  when: ansible_os_family == "RedHat" 
  tags: [ smtpd, nullmailer ]

- name: Install nullmailer repo (RedHat Family)
  yum_repository:
    name: "nullmailer"
    description: "p_conrad's Home Project (Fedora_22)"
    baseurl: "{{ nullmailer_repo_url }}"
    gpgkey: "{{  nullmailer_repo_gpg_key_url }}"
    gpgcheck: yes
  when: ansible_os_family == "RedHat" and not nullmailer_repofile_result.stat.exists
  tags: [ smtpd, nullmailer ]

- name: Import nullmailer GPG key (RedHat Family)
  rpm_key:
    key: "{{ nullmailer_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == "RedHat" and not nullmailer_repofile_result.stat.exists
  tags: [ smtpd, nullmailer ]

- name: install nullmailer (Debian family)
  apt: pkg=nullmailer state=latest
  when: ansible_os_family == "Debian"
  tags: [ smtpd, nullmailer ]

- name: install nullmailer (RedHat family)
  yum: name={{ item }} state=present
  with_items:
      - nullmailer
      - mailx
  when: ansible_os_family == "RedHat" 
  tags: [ smtpd, nullmailer ]

# - name: install nullmailer
#   pkgng: name={{ item }} state=present cached=yes
#   with_items:
#     - nullmailer
#   when: ansible_distribution == "FreeBSD"
#   tags: [ smtpd, nullmailer ]

- name: install nullmailer from ports
  portinstall: name={{ item }} state=present use_packages=no
  with_items:
      - nullmailer
  when: ansible_distribution == "FreeBSD"
  tags: [ smtpd, nullmailer ]

- name: disable old FreeBSD sendmail services
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - sendmail
    # - sendmail_submit
    # - sendmail_outbound
    # - sendmail_msp_queue
  when: ansible_distribution == "FreeBSD"
  tags: [ smtpd, nullmailer ]

- name: activate nullmailer service
  service: name=nullmailer state=started enabled=yes
  tags: [ smtpd, nullmailer ]

- name: config nullmailer
  template: src=etc/{{ item }}.j2 dest={{ conf_local_etc_path }}/{{ item }} owner=root group={{ conf_root_group }} mode=0644
  with_items:
    - nullmailer/adminaddr
    - nullmailer/defaultdomain
    - nullmailer/remotes
    - mailname
  notify: handle_restart_nullmailer
  tags: [ smtpd, nullmailer ]

#
# TODO: We need to clean up some more.
#
# sendmail	/usr/local/libexec/nullmailer/sendmail
# send-mail	/usr/local/libexec/nullmailer/sendmail
# mailq		/usr/local/libexec/nullmailer/mailq
#

- name: config /etc/mail/mailer.conf
  replace: dest=/etc/mail/mailer.conf regexp='^(.*)\/libexec\/sendmail\/(.*)$' replace='\1/local/libexec/nullmailer/\2' backup=yes
  when: ansible_distribution == "FreeBSD"
  tags: [ smtpd, nullmailer ]

- name: restart nullmailer service
  service: name=nullmailer state=restarted enabled=yes
  tags: [ smtpd, nullmailer ]
