---

# file: playbooks/roles/common/tasks/nullmailer.yml

- name: nullmailer PPA (12.04 only)
  apt_repository: repo='ppa:mikko-red-innovation/ppa' update_cache=yes
  when: ansible_distribution_version == "12.04" and ansible_distribution == "Ubuntu"
  tags: [ smtpd, nullmailer ]

- name: install nullmailer
  apt: pkg=nullmailer state=latest
  when: ansible_os_family == "Debian"
  tags: [ smtpd, nullmailer ]

# - name: install nullmailer
#   pkgng: name={{ item }} state=present cached=yes
#   with_items:
#     - nullmailer
#   when: ansible_distribution == "FreeBSD"
#   tags: [ smtpd, nullmailer ]

- name: install nullmailer from ports
  portinstall: name={{ item }} state=present use_packages=no
  with_items:
      - nullmailer
  when: ansible_distribution == "FreeBSD"
  tags: [ smtpd, nullmailer ]

- name: disable old FreeBSD sendmail services
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - sendmail
    # - sendmail_submit
    # - sendmail_outbound
    # - sendmail_msp_queue
  when: ansible_distribution == "FreeBSD"
  tags: [ smtpd, nullmailer ]

- name: activate nullmailer service
  service: name=nullmailer state=started enabled=yes
  tags: [ smtpd, nullmailer ]

- name: config nullmailer
  template: src=etc/{{ item }}.j2 dest={{ conf_local_etc_path }}/{{ item }} owner=root group={{ conf_root_group }} mode=0644
  with_items:
    - nullmailer/adminaddr
    - nullmailer/defaultdomain
    - nullmailer/remotes
    - mailname
  notify: handle_restart_nullmailer
  tags: [ smtpd, nullmailer ]

#
# TODO: We need to clean up some more.
#
# sendmail	/usr/local/libexec/nullmailer/sendmail
# send-mail	/usr/local/libexec/nullmailer/sendmail
# mailq		/usr/local/libexec/nullmailer/mailq
#

- name: config /etc/mail/mailer.conf
  replace: dest=/etc/mail/mailer.conf regexp='^(.*)\/libexec\/sendmail\/(.*)$' replace='\1/local/libexec/nullmailer/\2' backup=yes
  when: ansible_distribution == "FreeBSD"
  tags: [ smtpd, nullmailer ]

- name: restart nullmailer service
  service: name=nullmailer state=restarted enabled=yes
  tags: [ smtpd, nullmailer ]
