---

# file: playbooks/roles/common/tasks/rc_local.yml

- name: update init script
  template:
    src: etc/rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
    validate: '/usr/bin/env sh -n %s'
  notify: handle_start_rc_local
  tags: [ rc-local, rc-local-conf ]

- name: enable service
  service:
    name: rc.local
    enabled: true
  when:
    - ansible_os_family == "Debian"
    - ansible_service_mgr == 'systemd'
  tags: [ rc-local, rc-local-conf ]