---

# file: playbooks/roles/common/tasks/redis.yml

# - name: Include OS-specific variables
#   include_vars: "{{ ansible_os_family }}.yml"

- name: define redis_package
  set_fact:
    redis_package: "{{ __conf_redis_package }}"
  when: redis_package is not defined
  tags: [ redis ]

# - include: setup-RedHat.yml
#   when: ansible_os_family == 'RedHat'

- name: ensure redis is installed
  apt:
    name: "{{ redis_package }}"
    state: present
  when: ansible_os_family == 'Debian'
  tags: [ redis ]

- name: ensure redis is configured
  template:
    src: etc/redis/redis.conf.j2
    dest: "{{ conf_redis_conf_path }}"
    mode: 0644
  notify: handle_restart_redis
  tags: [ redis, redis-conf ]

- name: ensure redis is running and enabled on boot
  service: "name={{ conf_redis_daemon }} state=started enabled=yes"
  tags: [ redis ]
