---

# file: playbooks/roles/common/tasks/shared.yml

- name: ensure shared files are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  when: item.state|default('present') != 'absent'
  with_items: "{{ conf_shared_files }}"
  tags: [ shared, shared-conf ]
