- name: install snmpd (Debian family)
  apt: pkg={{ item }} state=latest
  with_items:
    - snmp
    - snmpd
  when: ansible_os_family == "Debian"
  tags: [ snmpd ]

- name: activate snmpd service
  service: name=snmpd state=started enabled=yes
  tags: [ snmpd ]

- name: create /etc/snmp
  file: path=/etc/snmp state=directory owner=root group={{ conf_root_group }} mode=0755
  tags: [ snmpd ]

- name: deploy configs
  template: src=etc/snmp/{{ item }}.j2 dest=/etc/snmp/{{ item }} owner=root group={{ conf_root_group }} mode=0600
  with_items:
    - snmpd.conf
    - snmptrapd.conf
  tags: [ snmpd ]
